# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SEEK_R' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'BigInt', '~> 2.1'
  # Pods for SEEK_R

  target 'SEEK_RTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SEEK_RUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
